# Generated by Django 5.0.6 on 2024-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_updated_at_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
